on: [push]
jobs:
  contents:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Création de Q3_archive_java.txt et ajout de son contenu
        run: |
          echo "Trystan Baillobay" > Q3_archive_java.txt
          javac Q3.java
          java Q3 5 >> Q3_archive_java.txt
      
      - name: Commit et push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config pull.rebase false
          git pull
          git config --global user.name ydroo
          git config --global user.email baillobaytrystan06@gmail.com
          git add Q3_archive_java.txt
          git add Q3.class
          git commit -m "Ajout de Q3_archive_java.txt"
          git push
